### ISSUE TITLE
directivebreakdown logic should condense `allocationCount` when an explicit `count` of a resource is requested

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#332]
@matthew-richerson reported an issue found by a user:

> I think there might be an issue if you list the same OST twice in the servers resource rather than listing it once and giving a count of 2 :

```
    storage:
    - allocationCount: 1
      name: tuolumne225
    - allocationCount: 1
      name: tuolumne225
```
vs:
```
    storage:
    - allocationCount: 2
      name: tuolumne225
```
